import React, { useEffect, useState } from "react";
import axios from "axios";
import { FileText, ExternalLink } from "lucide-react";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

export default function RecentReports() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    const load = async () => {
      try {
        const { data } = await axios.get(`${API}/reports?limit=6`);
        if (mounted) setReports(data || []);
      } catch {
        /* silent */
      } finally {
        if (mounted) setLoading(false);
      }
    };
    load();
    const t = setInterval(load, 12000); // poll
    return () => { mounted = false; clearInterval(t); };
  }, []);

  if (!loading && !reports.length) return null;

  return (
    <section
      id="recent"
      data-testid="recent-reports-section"
      className="py-24 md:py-32 border-t border-white/10"
    >
      <div className="max-w-7xl mx-auto px-6 lg:px-10">
        <div className="flex items-end justify-between mb-12 flex-wrap gap-6">
          <div>
            <p className="text-overline mb-4">// Recently Generated</p>
            <h2 className="font-serif text-4xl md:text-5xl tracking-tight">
              Latest reports off the press.
            </h2>
          </div>
          <p className="text-[#8C9BB0] max-w-md text-sm">
            Reports auto-generated by Bull-AI from uploaded filings. Click any card to re-download the PDF.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-px bg-white/10 border border-white/10">
          {reports.map((r) => (
            <a
              key={r.id}
              data-testid="report-card"
              href={`${API}/report/${r.id}/pdf`}
              target="_blank"
              rel="noopener noreferrer"
              className="bg-[#0A111A] p-6 flex flex-col gap-4 hover:bg-[#111A26] transition-colors group"
            >
              <div className="flex items-start justify-between">
                <FileText size={20} className="text-[#00F0FF]" />
                <ExternalLink size={14} className="text-[#8C9BB0] group-hover:text-white transition-colors" />
              </div>
              <div>
                <div className="font-serif text-xl text-white leading-tight">{r.company_name}</div>
                <div className="font-mono text-[0.7rem] uppercase tracking-[0.18em] text-[#8C9BB0] mt-1">
                  {r.report_title || "Research Note"}
                </div>
              </div>
              <div className="flex items-center justify-between font-mono text-xs mt-auto pt-4 border-t border-white/5">
                <div className="flex gap-4">
                  <span className="text-[#D4AF37]">{r.rating || "—"}</span>
                  <span className="text-white">{r.target_price || "—"}</span>
                </div>
                <span className="text-[#8C9BB0]">
                  {(r.file_size / 1024).toFixed(0)} KB
                </span>
              </div>
            </a>
          ))}
        </div>
      </div>
    </section>
  );
}
